[package]
name = "png_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.21.3", features = ["__screenshot"] }
image = "0.24.5"
rfd = "0.11.2"
